# Generated by Django 2.2.5 on 2022-01-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('board_title', models.CharField(max_length=50)),
                ('board_content', models.CharField(max_length=2000)),
                ('board_date', models.DateField()),
            ],
            options={
                'db_table': 'rental_board',
                'managed': False,
            },
        ),
    ]
