# Generated by Django 2.2.5 on 2022-01-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20220126_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_index', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Object',
                'managed': False,
            },
        ),
    ]
