# Generated by Django 2.2.5 on 2022-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('l_posting_index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('deposit', models.IntegerField(default=0, null=True)),
                ('pic', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Lender_Post',
                'managed': False,
            },
        ),
    ]
