# Generated by Django 2.2.5 on 2022-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_index', models.IntegerField()),
                ('user_id', models.CharField(max_length=255)),
                ('pw', models.CharField(max_length=100)),
            ],
        ),
    ]
