# Generated by Django 2.2.5 on 2022-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_borrower_borrower_chatting_lender_lender_chatting_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
