# Generated by Django 2.2.5 on 2022-01-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='borrower',
            table='Borrower',
        ),
        migrations.AlterModelTable(
            name='borrower_chatting',
            table='B_Post_Chat',
        ),
        migrations.AlterModelTable(
            name='lender',
            table='Lender',
        ),
        migrations.AlterModelTable(
            name='lender_chatting',
            table='L_Post_Chat',
        ),
        migrations.AlterModelTable(
            name='object',
            table='Object',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
