# Generated by Django 2.2.5 on 2022-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220125_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
