# Generated by Django 2.2.5 on 2022-01-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220125_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_chatting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lender_chatting',
            name='id',
        ),
        migrations.AddField(
            model_name='borrower_chatting',
            name='b_chatting_index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='borrower_chatting',
            name='posting_index',
            field=models.ForeignKey(db_column='posting_index', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Borrower', to='app.Borrower'),
        ),
        migrations.AddField(
            model_name='lender_chatting',
            name='l_chatting_index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='lender_chatting',
            name='posting_index',
            field=models.ForeignKey(db_column='posting_index', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Lender', to='app.Lender'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='b_posting_index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lender',
            name='l_posting_index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_index',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
