# Generated by Django 2.2.5 on 2022-01-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220125_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_chatting',
            name='posting_index',
        ),
        migrations.RemoveField(
            model_name='lender_chatting',
            name='posting_index',
        ),
    ]
