# Generated by Django 2.2.5 on 2022-01-26 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220125_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='object',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='object',
            name='longitude',
        ),
        migrations.AddField(
            model_name='borrower',
            name='addr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='addr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='addr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='b_posting_index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='borrower_index',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='borrower_chatting',
            name='b_chatting_index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lender',
            name='body',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='l_posting_index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lender_index',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='lender_chatting',
            name='l_chatting_index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
