# Generated by Django 2.2.5 on 2022-01-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220126_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='borrower_index',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='lender_index',
        ),
    ]
