# Generated by Django 2.2.5 on 2022-01-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220126_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='addr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrower_chatting',
            name='chatting',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lender',
            name='pic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lender_chatting',
            name='chatting',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='addr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=100),
        ),
    ]
