# Generated by Django 2.2.5 on 2022-01-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_borrower_borrower_chatting_lender_lender_chatting_object_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='rentalfee',
            new_name='deposit',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='rental_fee',
            new_name='deposit',
        ),
    ]
