# Generated by Django 2.2.5 on 2022-01-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0018_auto_20220126_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('b_posting_index', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('body', models.CharField(max_length=255, null=True)),
                ('addr', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower_Chatting',
            fields=[
                ('b_chatting_index', models.IntegerField(primary_key=True, serialize=False)),
                ('user_index', models.IntegerField()),
                ('object_num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chatting', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('l_posting_index', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(max_length=255, null=True)),
                ('deposit', models.IntegerField()),
                ('addr', models.CharField(max_length=100, null=True)),
                ('object_num', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lender_Chatting',
            fields=[
                ('l_chatting_index', models.IntegerField(primary_key=True, serialize=False)),
                ('user_index', models.IntegerField()),
                ('object_num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chatting', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_index', models.IntegerField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255, null=True)),
                ('posting_index', models.IntegerField()),
                ('category', models.CharField(max_length=255, null=True)),
                ('deposit', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
                ('lender_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('addr', models.CharField(max_length=100, null=True)),
                ('pw', models.CharField(max_length=100)),
            ],
        ),
    ]
