# Generated by Django 2.2.5 on 2022-01-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220126_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='object',
            name='addr',
        ),
    ]
