# Generated by Django 2.2.5 on 2022-01-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220126_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lender_index',
            field=models.IntegerField(),
        ),
    ]
