# Generated by Django 2.2.5 on 2022-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220126_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
