# Generated by Django 2.2.5 on 2022-01-26 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220126_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower_chatting',
            name='chatting',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='lender_index',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='lender_chatting',
            name='chatting',
            field=models.TextField(null=True),
        ),
    ]
