# Generated by Django 2.2.5 on 2022-01-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220126_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrower_index',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
