# Generated by Django 2.2.5 on 2022-01-26 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220126_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='posting_index',
            field=models.ForeignKey(db_column='l_posting_index', on_delete=django.db.models.deletion.CASCADE, to='app.Lender'),
        ),
    ]
