# Generated by Django 2.2.5 on 2022-01-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_lender_object_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='deposit',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
