# Generated by Django 2.2.5 on 2022-01-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0042_auto_20220126_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('b_posting_index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Borrower_Post',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('l_posting_index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('deposit', models.IntegerField(default=0, null=True)),
                ('pic', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Lender_Post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('register_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_index', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('deposit', models.IntegerField()),
                ('lender_index', models.IntegerField()),
                ('posting_index', models.ForeignKey(db_column='l_posting_index', on_delete=django.db.models.deletion.CASCADE, to='app.Lender')),
            ],
            options={
                'db_table': 'Object',
            },
        ),
        migrations.CreateModel(
            name='Lender_Chatting',
            fields=[
                ('l_chatting_index', models.AutoField(primary_key=True, serialize=False)),
                ('user_index', models.IntegerField()),
                ('object_num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chatting', models.TextField(null=True)),
                ('lender_index', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('posting_index', models.ForeignKey(db_column='l_posting_index', on_delete=django.db.models.deletion.CASCADE, to='app.Lender')),
            ],
            options={
                'db_table': 'Lender_Chatting',
            },
        ),
        migrations.AddField(
            model_name='lender',
            name='lender_index',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.CreateModel(
            name='Borrower_Chatting',
            fields=[
                ('b_chatting_index', models.AutoField(primary_key=True, serialize=False)),
                ('user_index', models.IntegerField()),
                ('object_num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chatting', models.TextField(null=True)),
                ('borrower_index', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('posting_index', models.ForeignKey(db_column='b_posting_index', on_delete=django.db.models.deletion.CASCADE, to='app.Borrower')),
            ],
            options={
                'db_table': 'Borrower_Chatting',
            },
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrower_index',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
