# Generated by Django 2.2.5 on 2022-01-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20220127_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='borrower_chatting',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lender',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lender_chatting',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
