# Generated by Django 2.2.5 on 2022-01-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_index', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=50)),
                ('register_date', models.DateTimeField()),
            ],
        ),
    ]
