# Generated by Django 2.2.5 on 2022-01-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('register_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
