# Generated by Django 2.2.5 on 2022-01-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20220126_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=255),
        ),
    ]
