# Generated by Django 2.2.5 on 2022-01-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stuff',
        ),
        migrations.AddField(
            model_name='post',
            name='stuff_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
