# Generated by Django 2.2.5 on 2022-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20220126_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('l_posting_index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('deposit', models.IntegerField(default=0, null=True)),
                ('pic', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Lender_Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_index', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('deposit', models.IntegerField()),
                ('lender_index', models.IntegerField()),
            ],
            options={
                'db_table': 'Object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='member',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Stuff',
        ),
    ]
